version: 2

models:
  - name: stg_xkcd_comics
    description: "Staging model to load comic data."
    columns:
      - name: comic_id
        description: "Unique ID for each comic and a primary key."
        tests: [not_null, unique]
      - name: title
        description: "Title of each comic and not-null."
        tests: [not_null]
      - name: title_cleaned
        description: "Title after cleaning HTML tags."
        tests: [ not_null ]
      - name: title_letter_count
        description: "Number of alphabetic characters in the cleaned title."
        tests:
          - not_null
      - name: year
        description: "Comic publication year."
        tests: [not_null]
      - name: month
        description: "Comic publication month."
        tests: [not_null]
      - name: day
        description: "Comic publication day."
        tests: [not_null]

  - name: dim_date
    description: "A dimension table built from the XKCD comic publication dates."
    columns:
      - name: date_id
        description: " A Surrogate key generated in YYYYMMDD format, a Pkey."
        tests: [not_null, unique]
      - name: date
        description: "Formatted date string in YY-MM-DD format."
        tests: [not_null]
      - name: year
        description: "Year part of the date."
        tests: [not_null]
      - name: month
        description: "Month component of the date."
        tests:
          - not_null
          - accepted_values:
              values: [1,2,3,4,5,6,7,8,9,10,11,12]
      - name: day
        description: "Day component of the date."
        tests:
          - not_null
          - accepted_values:
              values: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]

  - name: dim_comic
    description: "Dimension with core information like title, publication date, image etc."
    columns:
      - name: comic_id
        description: "Unique ID of each comic and Pkey"
        tests: [not_null, unique]
      - name: date_id
        description: "publication date of comic in yymmdd and Fkey to dim_date."
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_id


  - name: dim_comic_text_enrichment
    description: "Stores enriching data for comics like transcript, alt text, news."
    columns:
      - name: comic_id
        description: "Unique ID for comics and Fkey to the dim_comic table."
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('dim_comic')
              field: comic_id

  - name: fact_comic_stats
    description: "A fact table storing crucial metrics like cost, views, review score of each comic"
    columns:
      - name: stats_id
        description: "Surrogate key for comic row."
        tests: [not_null, unique]

      - name: comic_id
        description: "Unique ID for comic and Fkey to the dim_comic."
        tests:
          - not_null
          - relationships:
              to: ref('dim_comic')
              field: comic_id

      - name: cost_eur
        description: "Computed by title_length * 5(euros) and always be >0."
        tests:
          - not_null

      - name: views
        description: "View count per comic generated as a random number between 0 and 10000."
        tests:
          - not_null
          - dbt_utils.expression_is_true("views BETWEEN 0 AND 10000")

      - name: review_score
        description: "Review score generated as  a random number between 1.0 and 10.0."
        tests:
          - not_null
          - validate_review_score

      - name: created_at
        description: "Timestamp when the metrics are generated."
        tests: [not_null]
