xkcd_comic_dbt:
  target: dev
  outputs:

    dev:
      type: sqlite
      threads: 1
      database: comics_xkcd.db
      schema: 'main'
      schemas_and_paths:
        main: ../data/comics_xkcd.db
      schema_directory: ../data

    prod:
      type: sqlite
      threads: 1
      database: comics_xkcd.db
      schema: 'main'
      schemas_and_paths:
        main: ../data/comics_xkcd.db
      schema_directory: ../data

